-------------------------------------------------------------------------------
Test set: br.unifesp.maritaca.persistence.entitymanager.OAuthTokenEntityTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.005 sec <<< FAILURE!
br.unifesp.maritaca.persistence.entitymanager.OAuthTokenEntityTest  Time elapsed: 1.053 sec  <<< ERROR!
java.io.IOError: org.apache.cassandra.config.ConfigurationException: Attempt to assign id to existing column family.
	at org.apache.cassandra.config.Schema.load(Schema.java:97)
	at me.prettyprint.hector.testutils.EmbeddedSchemaLoader.loadSchema(EmbeddedSchemaLoader.java:37)
	at me.prettyprint.hector.testutils.EmbeddedServerHelper.loadSchemaFromYaml(EmbeddedServerHelper.java:177)
	at me.prettyprint.hector.testutils.EmbeddedServerHelper.setup(EmbeddedServerHelper.java:64)
	at br.unifesp.maritaca.persistence.cassandra.BaseEmbededServerSetupTest.setup(BaseEmbededServerSetupTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: org.apache.cassandra.config.ConfigurationException: Attempt to assign id to existing column family.
	at org.apache.cassandra.config.Schema.load(Schema.java:380)
	at org.apache.cassandra.config.Schema.load(Schema.java:93)
	... 27 more

